### ISSUE TITLE
Suggestion for buy order placement

### ISSUE THREAD

**Issue by YTmaxord0076** [ianrenton/Skyblock-Bazaar-Flipping-Calculator#12]
Having the max quantity you can buy with the money you have exceeding the max place order makes it a bit annoying to place the last order, so I suggest having the number of maxed orders + the extra amount for easier reading
![image](https://github.com/ianrenton/Skyblock-Bazaar-Flipping-Calculator/assets/85416719/ed60abe5-8319-4758-9fdc-b60c092def55)
You could easily just divide the whole number by 71680 showing just the whole number and add the extra to reach that quantity.
So with this new system, you won't have to mess around with the last order to know how much you can afford

**Comment by ianrenton** [comment]
Sounds good! I think I would prefer the notation to be a bit longer and self-explanatory, e.g. under "Number of Offers" it could show "7x Max + 1 of 24555" or something like that - would that work for you?

**Comment by YTmaxord0076** [comment]
Yeah that would work great, that way you won't have to mess around with the last offer

**Comment by ianrenton** [comment]
Hi, sorry for the long delay in implementing this! I have updated the software to look like this - please let me know if that meets your needs.
![image](https://github.com/ianrenton/Skyblock-Bazaar-Flipping-Calculator/assets/503149/bd2117f1-969f-4670-8473-098600308a08)

**Comment by ianrenton** [comment]
No reply after 6 weeks, closing issue
