### ISSUE TITLE
Slothpixel API

### ISSUE THREAD

**Issue by ianrenton** [ianrenton/Skyblock-Bazaar-Flipping-Calculator#2]
We may at some point be able to use the Slothpixel API which does not require an API key for basic access. However its CORS policy currently prevents remotely querying the API from the browser using JS.

**Comment by Henry-Santa** [comment]
### No need to implement the slothpixel api!
Hey, you do not need an api key to use the regular hypixel api (for the bazaar endpoint)! I created a pull request not too long ago removing your api key from the code (that was a really unsecure way of storing it!). I hope this comment lets you close your **only** open issue! I hope this helps

**Comment by ianrenton** [comment]
Thanks, tested and it does indeed work without an API key. Code updated.
