### ISSUE TITLE
Buy order and sell order price are flipped on the website

### ISSUE THREAD

**Issue by Jbo201747** [ianrenton/Skyblock-Bazaar-Flipping-Calculator#7]
See above. 
On the website, the numbers for the buy price of items and the sell price are reversed.
See example below:
Website:
https://imgur.com/a/WWZii8M
In-game stats:
https://imgur.com/a/8qc7k8u

As seen with the above imgur links, the current statistics on the website is correct, but their positions are swapped.

Text-based comparison below
item: Frail 6

**Website:**
Buy price: 7.2 coins
Sell price: 639.1 coins

**In-game**
Buy price: 639.1 coins
Sell price: 7.2 coins
I'm relatively new to posting issues, so please forgive me if anything seems wrong about this post.
Thanks!

**Comment by ianrenton** [comment]
Hi, I've just fired up Minecraft to check this for the first time in about two years, and it does seem you're correct! Only took me 5 minutes to remember where the Bazaar trader is in Skyblock too :)

The API seems to have a "quick_status" element for each item now, which it may not have done when I first wrote this, and it does seem like that data is what's used in the game - the correct way around.

I will get that fixed ASAP... I wonder how long this problem has been around for without anyone noticing!

**Comment by ianrenton** [comment]
Having thought about it a bit more, I actually think the current behaviour is correct. If I understand correctly, Bazaar Flipping involves putting in a buy order priced at or above the current highest buy order (which is what appears in your screenshot as the _sell_ instantly price) then putting in a sell offer priced at or below the current lowest sell offer (which is what appears in your screenshot as the _buy_ price). As a Bazaar Flipper, the people using "buy instantly" and "sell instantly" are your "customers"; so the prices are the other way around.

For example, flipping carrots, the equivalent to your screenshot is this:

![image](https://user-images.githubusercontent.com/503149/188147305-13e483ed-0d86-486b-a276-b35e21cce462.png)

But to make a profit off the people who buy and sell instantly, I want to put in a _buy_ order at 1.8 or 1.9 so I become top of the list for people looking to _sell_ instantly:

![image](https://user-images.githubusercontent.com/503149/188148223-435604c1-caa1-48c9-91a5-44d857583cbb.png)

Then I want to put in a _sell_ offer at 2.7 or 2.6 so I'm top of the list for people looking to _buy_ instantly:

![image](https://user-images.githubusercontent.com/503149/188148589-afb7b774-bcdd-422a-b3d8-5ed9f9a64e18.png)

Assuming all goes well, this then results in a profit to me - as shown in the calculator.

![image](https://user-images.githubusercontent.com/503149/188148775-00297568-3371-43f0-8a27-31ae8ec47c78.png)

Hopefully that makes sense - it fries my brain thinking about it :)

**Comment by Jbo201747** [comment]
Ohhh, ok! I think I understand. Didn't realize the menus were set-up that way. Thanks for checking, though!
And thanks for making such a great site!
