### ISSUE TITLE
Add an option to exclude enchantments

### ISSUE THREAD

**Issue by AnOrinaryCabbage** [ianrenton/Skyblock-Bazaar-Flipping-Calculator#8]
Due to the new skyblock update, you can now buy enchantments from the bazaar and the price difference between buy and sell orders are usually high, which puts most enchantments in the top (sort by profit) but they usually sells very slowly (like, 1 or 2 enchanted book every hour?) so if you add an option to exclude enchantments from the list then i'd really appreciate it

**Comment by ianrenton** [comment]
Sure, no problem!

**Comment by ianrenton** [comment]
Change complete, please let me know and close this issue if you're happy with it :)

**Comment by AnOrinaryCabbage** [comment]
Thanks, now i don't have to scroll through every single enchantments again :)
