### ISSUE TITLE
Add an option to remove potentially manipulated items

### ISSUE THREAD

**Issue by ethanready** [ianrenton/Skyblock-Bazaar-Flipping-Calculator#9]
You could check the difference in buy and sell price of an item every hour over the last day to get an average, and then if the difference was greater than 120% of the average difference, it would be suspected that the item was manipulated and you could exclude it

**Comment by ethanready** [comment]
oh, yeah, i suppose thats a good point. mby i'll fork and see if i can find another way to do this

**Comment by ianrenton** [comment]
Can this issue be closed now PR #11 is merged?

**Comment by ethanready** [comment]
yeah
